name: mpi test
on:
  push:
    branches: [ main, yus/add_perfstubs ]

jobs:
  mpi-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install MPICH
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich libmpich-dev
      # - name: Setup MPI
      #   uses: mpi4py/setup-mpi@v1
      #   with:
      #     mpi: mpich

      - name: Build MPI program
        run: |
          mpicc test_mpi.c -o test_mpi
      - name: Run MPI
        run: |
          mpirun -n 2 ./test_mpi